#!/bin/sh
git commit . -m "(autocommitting before attempting publication)";
if [ "$(git rev-parse HEAD)" = "$(git rev-parse master)" ]; then
	sudo python2.6 setup.py clean build sdist install &&
	sudo python2.7 setup.py clean build sdist upload;
else
	echo "Attempting to publish non-master branch."
	false
fi
